<?php
/**
 * @file prmptr.inc Prompt templating with Azure/OpenAI.
 * @author Stackware, LLC
 * @version 5.0
 * @copyright Copyright (c) 2012-2023 Stackware, LLC. All Rights Reserved.
 * @copyright Licensed under the GNU General Public License
 * @copyright See COPYRIGHT.txt and LICENSE.txt.
 */
namespace asm;


class prompt extends \asm\Template
{

}
class prmptr extends \asm\TemplateSet
{

}

